# Generated by Django 5.2 on 2025-06-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('남아', '남아'), ('여아', '여아')], max_length=10, null=True)),
                ('neutered', models.CharField(blank=True, choices=[('완료', '완료'), ('미완료', '미완료'), ('모름', '모름')], max_length=10, null=True)),
                ('disease_history', models.TextField(blank=True, null=True)),
                ('living_period', models.CharField(blank=True, choices=[('1년 미만', '1년 미만'), ('3년 미만', '3년 미만'), ('10년 미만', '10년 미만'), ('10년 이상', '10년 이상')], max_length=30, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('housing_type', models.CharField(blank=True, choices=[('아파트', '아파트'), ('단독주택', '단독주택'), ('빌라/다세대', '빌라/다세대'), ('기타', '기타')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dogbreed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
